# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: election.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'election.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65lection.proto\"2\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"5\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"<\n\x0bVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63\x61ndidate_score\x18\x02 \x01(\x02\"$\n\x0cVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\"*\n\x12WorkRequestMessage\x12\x14\n\x0crequester_id\x18\x01 \x01(\t\"6\n\x0eWorkAssignment\x12\x13\n\x0b\x61ssigned_to\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\"\x1e\n\x0bTaskMessage\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"&\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xc8\x01\n\x0f\x45lectionService\x12\x32\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse\x12*\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\r.VoteResponse\x12\x33\n\x0bWorkRequest\x12\x13.WorkRequestMessage\x1a\x0f.WorkAssignment\x12 \n\nAssignTask\x12\x0c.TaskMessage\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'election_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=18
  _globals['_HEARTBEATREQUEST']._serialized_end=68
  _globals['_HEARTBEATRESPONSE']._serialized_start=70
  _globals['_HEARTBEATRESPONSE']._serialized_end=123
  _globals['_VOTEREQUEST']._serialized_start=125
  _globals['_VOTEREQUEST']._serialized_end=185
  _globals['_VOTERESPONSE']._serialized_start=187
  _globals['_VOTERESPONSE']._serialized_end=223
  _globals['_WORKREQUESTMESSAGE']._serialized_start=225
  _globals['_WORKREQUESTMESSAGE']._serialized_end=267
  _globals['_WORKASSIGNMENT']._serialized_start=269
  _globals['_WORKASSIGNMENT']._serialized_end=323
  _globals['_TASKMESSAGE']._serialized_start=325
  _globals['_TASKMESSAGE']._serialized_end=355
  _globals['_ACK']._serialized_start=357
  _globals['_ACK']._serialized_end=395
  _globals['_ELECTIONSERVICE']._serialized_start=398
  _globals['_ELECTIONSERVICE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
